# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20181002_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=models.TextField(),
        ),
    ]
